vich_uploader:
    db_driver: orm
    twig: true
    mappings:
        product_image:
            uri_prefix: '/e_commerce/public/images/products'
            upload_destination: '/public/images/products'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            directory_namer: ~
            inject_on_load: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
